models.py
from app import db
from datetime import datetime
import re


def slugify(s):
	pattern = r'[^\w+]'
	return re.sub(pattern, '-', s)


# create relationships many to many
post_tags = db.Table('post_tags', 
			db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
			db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),

			)





class Post(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	title = db.Column(db.String(140))
	slug = db.Column(db.String(140), unique=True)
	body = db.Column(db.Text)
	created = db.Column(db.DateTime, default=datetime.now())

	def __init__(self, *args, **kwargs):
		super(Post, self).__init__(*args, **kwargs)
		self.generate_slug()

	# part to relationships many to many
	tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts'), lazy='dynamic')


	def generate_slug(self):
		if self.title:
			self.slug = slugify(self.title)

	def __repr__(self):
		return '<Post id: {}, title: {}>'.format(self.id, self.title)


class Tag(db.Model):
	id = db.Column(db.Integer, primary_key=True)
	tag_name = db.Column(db.String(100)) 
	tag_slug = db.Column(db.String(100)) 

	def __init__(self, *args, **kwargs):
		super(Tag, self).__init__(*args, **kwargs)
		self.tag_slug = slugify(self.tag_name)

	def __repr__(self):
		return '<Tag id: {}, tag_name: {}>'.format(self.id, self.tag_name)




class Currency(db.Model):
	id = db.Column(db.Integer, primary_key = True)
	currency_name = db.Column(db.String(100))
	currency_value = db.Column(db.Float)
	currency_date = db.Column(db.DateTime, default=datetime.now())

	def __init__(self, *args, **kwargs):
		super(Currency, self).__init__(*args, **kwargs)


	def __repr__(self):
		return '<currency id: {}, currency_name: {}>'.format(self.id, self.currency_name)

dashbord/forms.py
from wtforms import Form, StringField, TextAreaField, IntegerField, SelectField
from models import Currency


class CurrencyForm(Form):
	"""docstring for PostForm"""


	currency_name = SelectField(u'Currency', choices=[
		('/USD/ILS/','USD to ILS'), 
		('/ILS/RUB/','ILS to RUB'), 
		])

posts/forms.py
from wtforms import Form, StringField, TextAreaField, IntegerField, SelectField
from models import Post, Tag

# Create fields for web form
class PostForm(Form):
	"""docstring for PostForm"""

	title = StringField('Title')
	body = TextAreaField('Body')

class TagForm(Form):
	posts = Post.query.all()

	mass=[]
	for post in posts:
		post.title
		tuple_1 = post.title
		mass.append(tuple_1)
		tuple_1 = 0

	tag_name = StringField('Tag name')
	posts_for_tag = SelectField(u'posts_for_tag', choices=mass)

app.py
from flask import Flask 
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

#  Create application
app = Flask(__name__) 
app.config.from_object(Configuration)

# connect ORM for DB
db = SQLAlchemy(app)


# Make migrations
migrate = Migrate(app, db)

# Create command for migrations
manager = Manager(app)
manager.add_command('db', MigrateCommand)

dashbord/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Currency
from .forms import CurrencyForm

from flask import request
from app import db

from flask import redirect
from flask import url_for

from functions import *


dashbord = Blueprint('dashbord', __name__, template_folder ='templates' )


@dashbord.route('/', methods = ['POST', 'GET'])
def index():
	if request.method == 'POST':






		new_currency = request.form['currency_name']
		funcstart = get_content(ready_url(main_url, new_currency))
		print(funcstart)

		new_value = round(float(funcstart), 3)

		print(new_value)

		try:
			currency_note = Currency(currency_name = new_currency, currency_value = new_value)
			db.session.add(currency_note)
			db.session.commit()
		except:
			print('something went wrong')
		return redirect(url_for('dashbord.index'))

	else:
		form = CurrencyForm()

		graph_usd_to_ils = Currency.query.filter(Currency.currency_name == '/USD/ILS/').order_by(db.desc(Currency.currency_date)).limit(7)

		graph_ils_to_rub = Currency.query.filter(Currency.currency_name == '/ILS/RUB/').order_by(db.desc(Currency.currency_date)).limit(7)
		


		mass_dates_rev_u_i, mass_currency_rev_u_i = reverce_val(graph_usd_to_ils)


		mass_dates_rev_i_r, mass_currency_rev_i_r = reverce_val(graph_ils_to_rub)



		return render_template('dashbord/index.html', 
			form = form, 
			currency_usd_to_ils = graph_usd_to_ils,
			currency_ils_to_rub = graph_ils_to_rub, 

			mass_dates = mass_dates_rev_u_i, 
			mass_currency = mass_currency_rev_u_i, 

			mass_dates_2 = mass_dates_rev_i_r, 
			mass_currency_2 = mass_currency_rev_i_r, 
			)

main.py
from app import app
from app import db
from posts.blueprint import posts
from dashbord.blueprint import dashbord
import view


# create application (blueprint)
app.register_blueprint(posts, url_prefix='/blog')
app.register_blueprint(dashbord, url_prefix='/dashbord')

if __name__ == '__main__':
	app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template

from models import Post, Tag
from .forms import PostForm, TagForm

from flask import request
from app import db

from flask import redirect
from flask import url_for

# create folder for this app templates and register app prefix
posts = Blueprint('posts', __name__, template_folder='templates') 



@posts.route('/create-post', methods=['POST', 'GET'])
def create_post():

	if  request.method == 'POST':
		title = request.form['title']
		body = request.form['body']

		try:
			post = Post(title=title, body=body)
			db.session.add(post)
			db.session.commit()

		except:
			print('Something was wrong.')

		return redirect(url_for('posts.index'))


	form = PostForm()
	active_create_post = 'active'
	context= {
	'form': form,
	'active_create_post': active_create_post,
	}
	return render_template('posts/create_post.html', context = context)




@posts.route('/create-tag', methods=['POST', 'GET'])
def create_tag():
	if request.method == 'POST':
		tag_name = request.form['tag_name']
		posts_for_tag = request.form['posts_for_tag']
		post_for_tag = Post.query.filter(Post.title == posts_for_tag)
		post_for_tag = post_for_tag.first()
		try:
			tag = Tag(tag_name = tag_name)
			db.session.add(tag)
			db.session.commit()

			new_tag = Tag.query.filter(Tag.tag_name == tag_name)
			new_tag = new_tag.first()
			new_tag.posts.append(post_for_tag)
			db.session.add(new_tag)
			db.session.commit()

		except:
			print('Something was wrong with create tag')

		return redirect(url_for('posts.index'))
		

	else:
		form = TagForm()
		active_create_tag = 'active'
		posts = Post.query.all()
		context = {
		'form': form,
		'active_create_tag': active_create_tag,
		'posts': posts,
		}

		return render_template('posts/create_tag.html', context = context)




@posts.route('/')
def index():
	
	q = request.args.get('q')


	page = request.args.get('page')
	if page and page.isdigit():
		page = int(page)
	else:
		page = 1

	if q:
		posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) #.all()
	else:
		posts = Post.query.order_by(Post.created.desc())


	pages = posts.paginate(page = page, per_page = 5)


	active_blog = 'active'
	context = {
	'posts': posts,
	'active_blog': active_blog,
	'pages': pages,
	}
	return render_template('posts/index.html', context = context)



@posts.route('/<slug>')
def post_detail(slug):
	post_data = Post.query.filter(Post.slug == slug).first()
	post_tags = post_data.tags.all()
	context = {
	'post_data': post_data,
	'post_tags': post_tags,
	}
	return render_template('posts/post_detail.html', context = context)



@posts.route('/tag/<slug>')
def tag_detail(slug):
	tag_data = Tag.query.filter(Tag.tag_slug == slug).first()
	tag_posts = tag_data.posts
	context = {
	'tag_data': tag_data,
	'tag_posts': tag_posts
	}
	return render_template('posts/tag_detail.html', context = context)

dashbord/templates/dashbord/index.html
{% extends 'base.html' %}


{% block title %}
currency
{% endblock %}

{% block content_title %}
Currency
{% endblock %}

{% block content %}


<div class="col-md-4 mb-3 mt-2">

	<form action="{{ url_for('dashbord.index') }}" method="POST" class="form-inline">
		<div class="form-group ">
			{% for field in form %}
			<div class="form-group mx-sm-3">
				{{ field.label(class='control-label mx-sm-3') }}
				{{ field(class='form-control') }}
			</div>
			{% endfor %}
			<button class="btn btn-success " type="submitt">Update Currency</button>
		</div>
	</form>
</div>













<div class="col-md-12 ">
	<div class=" float-left col-md-6">



		<canvas id="myChart" width="200" height="100"></canvas>
		<script>
		var mass_dates = ['{{ mass_dates[0] }}', '{{ mass_dates[1] }}', '{{ mass_dates[2] }}', '{{ mass_dates[3] }}', '{{ mass_dates[4] }}', '{{ mass_dates[5] }}', '{{ mass_dates[6] }}'];
		var mass_currency = ['{{ mass_currency[0] }}', '{{ mass_currency[1] }}', '{{ mass_currency[2] }}', '{{ mass_currency[3] }}', '{{ mass_currency[4] }}', '{{ mass_currency[5] }}', '{{ mass_currency[6] }}'];
		var ctx = document.getElementById('myChart').getContext('2d');
		var chart = new Chart(ctx, {
		    // The type of chart we want to create
		    type: 'line',

		    // The data for our dataset
		    data: {
		        labels: mass_dates,
		        datasets: [{
		            label: 'USD to ILS',
		            backgroundColor: 'rgb(255, 99, 132)',
		            borderColor: 'rgb(255, 99, 132)',
		            data: mass_currency
		        }]
		    },

		    // Configuration options go here
		    options: {}
		});
		</script>

		<ul class="list-group ">
		{% for currency_one in currency_usd_to_ils %}

			<li class="list-group-item"> {{currency_one.currency_date.strftime('%Y-%m-%d %H-%M')}} : {{currency_one.currency_name}} : {{currency_one.currency_value}}</li>

		{% endfor %}
		</ul>
	</div>








	<div class="float-right col-md-6">


		<canvas id="myChart2" width="200" height="100"></canvas>
		<script>
		var mass_dates = ['{{ mass_dates_2[0] }}', '{{ mass_dates_2[1] }}', '{{ mass_dates_2[2] }}', '{{ mass_dates_2[3] }}', '{{ mass_dates_2[4] }}', '{{ mass_dates_2[5] }}', '{{ mass_dates_2[6] }}'];
		var mass_currency = ['{{ mass_currency_2[0] }}', '{{ mass_currency_2[1] }}', '{{ mass_currency_2[2] }}', '{{ mass_currency_2[3] }}', '{{ mass_currency_2[4] }}', '{{ mass_currency_2[5] }}', '{{ mass_currency_2[6] }}'];
		var ctx = document.getElementById('myChart2').getContext('2d');
		var chart = new Chart(ctx, {
		    // The type of chart we want to create
		    type: 'line',

		    // The data for our dataset
		    data: {
		        labels: mass_dates,
		        datasets: [{
		            label: 'LSD to RUB',
		            backgroundColor: '#007bff',
		            borderColor: '#007bff',
		            data: mass_currency
		        }]
		    },

		    // Configuration options go here
		    options: {}
		});
		</script>



		<ul class="list-group ">
		{% for currency_one in currency_ils_to_rub %}

			<li class="list-group-item"> {{currency_one.currency_date}} : {{currency_one.currency_name}} : {{currency_one.currency_value}}</li>

		{% endfor %}
		</ul>
	</div>
</div>







{% endblock %}

posts/templates/posts/create_post.html
{% extends 'base.html' %}


{% block title %}
Create Post
{% endblock %}

{% block content_title %}
	Create new Post
{% endblock %}

{% block content %}

<div class="col-md-6">

	<form action="{{ url_for('posts.create_post') }}" method="POST" >
		{% for field in context.form %}
		<div class="form-group">
			{{ field.label(class='control-label') }}
			{{ field(class='form-control') }}
		</div>
		{% endfor %}
		<button class="btn btn-success" type="submitt">Create Post</button>
	</form>
</div>
{% endblock %}

posts/templates/posts/create_tag.html
{% extends 'base.html' %}


{% block title %}
Create Tag
{% endblock %}

{% block content_title %}
	Create new Tag
{% endblock %}

{% block content %}

<div class="col-md-6">
		{% for post in context.posts %}
			{{ post.title }}
		{% endfor %}
	<form action="{{ url_for('posts.create_tag') }}" method="POST" >
		{% for field in context.form %}
		<div class="form-group">
			{{ field.label(class='control-label') }}
			{{ field(class='form-control') }}
		</div>
		{% endfor %}
		<button class="btn btn-success" type="submitt">Create Tag</button>
	</form>
</div>
{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}


{% block title %}

{% endblock %}

{% block content_title %}
	Posts
{% endblock %}

{% block content %}

 


	{% for post in context.pages.items %}
		<a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.title}}</a>
		<p>
			{{post.id}}
			{{post.body}}
			{{post.created}}
		</p>
	{% endfor %}




	<nav aria-label="...">
		<ul class="pagination">

			<li class="page-item {% if not context.pages.has_prev %}disabled{% endif %}">

				<a class="page-link" href="./?page={{ context.pages.prev_num }}" tabindex="-1" aria-disabled="true">Previous</a>

			</li>

			{% for page in context.pages.iter_pages() %}
			
			
			<li class="page-item {% if page == context.pages.page %}active{% endif %}">
				<a class="page-link" href="./?page={{ page }}">{{ page }}</a>
			</li>

			{% endfor %}


			<li class="page-item {% if not context.pages.has_next %}disabled{% endif %}">

				<a class="page-link" href="./?page={{ context.pages.next_num }}">Next</a>

			</li>

		</ul>
	</nav>






{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}


{% block title %}
	{{context.post_data.title}}
{% endblock %}

{% block content_title %}
	Post: 
{{context.post_data.title}}

{% endblock %}

{% block content %}
	<div class="tags">
		{% for tag in context.post_tags %}
			<a href="{{ url_for('posts.tag_detail', slug= tag.tag_slug) }}"><span class="badge badge-success">{{tag.tag_name}}</span></a>
		{% endfor %}
	</div>
	
	<div class="main-content">
		
		<p>{{context.post_data.body}}</p>
		<p>{{context.post_data.created}}</p>
		
	</div>

{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}


{% block title %}
	{{context.tag_data.tag_name}}
{% endblock %}

{% block content_title %}
	Tag: 
{{context.tag_data.tag_name}}

{% endblock %}

{% block content %}
	<div class="main-content">
		{% for post in context.tag_posts %}
			<a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.title}}</a>
			<p>{{post.body}}</p>
			<p>{{post.created}}</p>
		{% endfor %}
	</div>
	
		

{% endblock %}

posts/templates/posts/test.html
{% extends 'base.html' %}


{% block title %}

{% endblock %}

{% block content_title %}
	test
{% endblock %}

{% block content %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		
		{% block title %}

		{% endblock %} | Gillio app

	</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

	
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{{ url_for('index') }}">Gillio</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarTogglerDemo02">
			<ul class="navbar-nav  mt-2 mt-lg-0">
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a>
				</li>

			</ul>
			<ul class="navbar-nav  mt-2 mt-lg-0">
				<li class="nav-item">
					<a class="nav-link" href="{{ url_for('dashbord.index') }}">Dashbord <span class="sr-only">(current)</span></a>
				</li>

			</ul>


			<ul class="navbar-nav  mt-2 mt-lg-0">
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Create
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{{ url_for('posts.create_post') }}">+ Create Post</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="{{ url_for('posts.create_tag') }}">+ Create Tag</a>
					</div>
				</li>

			</ul>




			<form class="form-inline ml-auto my-2 my-lg-0" method='GET'>
				<input class="form-control mr-sm-2" type="search" placeholder="Search" name='q' value="{{ request.args.get('q', '') }}">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
		</div>
	</nav>




<div class="container">
	<div class="row">
		<h1>
			
		{% block content_title %}

		{% endblock %}

		</h1>
	</div>
	
	<div>
		{% block content %}

		{% endblock %}
	</div>
</div>







<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block title %}
index page
{% endblock %}


{% block content_title %}
Gillio header
{% endblock %}


{% block content %}
<p>last_post:  {{context.last_post.title }}</p>
<p>creation time:  {{context.last_time }}</p>
 






{% endblock %}